# Generated by Django 4.1.7 on 2023-02-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Nom_Epicerie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='epicerie', to='project.epicerie'),
        ),
    ]
