# Generated by Django 4.1.7 on 2023-02-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Nom_Epicerie',
            new_name='epicerie',
        ),
    ]
