# Generated by Django 4.1.7 on 2023-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='ID_Credit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epicerie',
            name='ID_Epicerie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='ID_Produit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
