# Generated by Django 4.1.7 on 2023-02-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_credit_id_credit_epicerie_id_epicerie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epicerie',
            old_name='Nom_Epicier',
            new_name='epicier',
        ),
    ]
