# Generated by Django 4.1.7 on 2023-02-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_nom_epicier_epicerie_epicier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='Nom_Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='Nom_Epicerie',
            new_name='epicerie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='Nom_Epicerie',
            new_name='epicerie',
        ),
    ]
