# Generated by Django 4.1.7 on 2023-02-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_nom_client_credit_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epicerie',
            name='ID_Epicerie',
        ),
    ]
