# Generated by Django 4.1.7 on 2023-02-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_epicerie_id_epicerie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='ID_Produit',
        ),
    ]
