# Generated by Django 4.1.7 on 2023-02-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_produit_id_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='ID_Credit',
        ),
    ]
